Thread lab
GrandpaKaseki/dist_sys pull request #2
Opened 2023-09-27 11:56 UTC by GrandpaKaseki

Task completed. But there are two issues. First one: during tests bitcoin course request time increases up to 22 seconds. Second one: if csv-file was opened in exel, cpu percentage values turns into dates.

2023-09-28 13:17 UTC, Crocussys commented
Ну то, что проценты превращаются в даты, это уже проблема екселя)

2023-10-02 18:26 UTC, Crocussys commented
Мне кстати кажется, что csv файл не должен находится PR

2023-10-20 07:45 UTC, arybin93 requested changes
В целом, хорошо. Оставил комментарии на улучшения

2023-10-20 07:45 UTC, arybin93 commented on .gitignore
> +id_rsa.pub
Пошарить публичный ключ, ещё не страшно. А вот приватный да.
Можешь настроить pre-commit для своего репозитория и используя хук: detect-private-key
Не позволит сделать коммит, если ключ был обнаружен в изменениях.

Через ,gitignore тоже вариант, только ключ может быть назван по другому

2023-10-20 07:45 UTC, arybin93 commented on main.py
> +    """This class collect info about usd→rub course from https://www.cbr-xml-daily.ru/daily_json.js."""
Docstring, круто!

2023-10-20 07:45 UTC, arybin93 commented on main.py
>          return requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()
Такого рода значения константные значения, лучше выносить в отдельную переменную:
https://www.cbr-xml-daily.ru/daily_json.js

2023-10-20 07:45 UTC, arybin93 commented on main.py
>          return requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()
Что если HTTP запрос придёт с ошибочным кодом?

2023-10-20 07:45 UTC, arybin93 commented on main.py
>  class CPUTrAcKeR:
Посмотри тоже в сторону абстрактного класса, модуль abc

2023-10-20 07:45 UTC, arybin93 commented on main.py
>          self.curr_usd = self.__get_usd_price()['Valute']['USD']['Value']
А зачем, забираем при инициализации объекта класса? 
Может просто self.curr_usd = None ? или = 0?

2023-10-20 07:45 UTC, arybin93 commented on main.py
> +            self.time_list.append(f"{time.localtime().tm_hour}:{time.localtime().tm_min}:{time.localtime().tm_sec}")
Может вызвать метод один раз time.localtime()
И потом из переменной доставать нужные значения?

Хотя лучше использовать модуль для работы с датами:
```
from datetime import datetime

now = datetime.now()

current_time = now.strftime("%H:%M:%S")
```

2023-10-20 07:45 UTC, arybin93 commented on main.py
> +    work_time_sec = 20 * 60  # how long will we collect (in seconds).
Константные значения лучше в верхнем регистре писать, по PEP 8.
WORK_TIME_SEC

2023-10-20 07:45 UTC, arybin93 commented on main.py
> +        if time.time() - time_count > work_time_sec:
Не пойму, сборщик только один раз отрабатывает?
Или после сохранения очередной порции продолжает работу?

2023-10-20 07:45 UTC, arybin93 commented on main.py
> +        """stops cycle from function start_collect, then saves lists into pandas dataframe."""
А можем ли мы, не останавливая сборку метрик и в другом потоке по сохранению, забирать текущее значение и очищать после записи? Возможно потребуется Lock, чтобы избежать race condition.

А так правильно, при stop_collect переключаем флаг. Не обязательно, только смешивать с сохранением.

2023-10-22 10:26 UTC, GrandpaKaseki commented on main.py
> +        if time.time() - time_count > work_time_sec:
Цикл прерывается, когда заданное время истекает. А так потоки собирают данные раз в минуту, в течение заданного времени

2023-10-22 11:21 UTC, GrandpaKaseki commented on .gitignore
> +id_rsa.pub
Ну через гитигнор проще, когда один работаешь в репозитории. Плюс не думаю, что вообще стоит хранить в папке с кодом приватный ключ. В данном случае, это нужно было для предыдущей лабы

2023-10-22 11:23 UTC, GrandpaKaseki commented on main.py
> +    work_time_sec = 20 * 60  # how long will we collect (in seconds).
Поправил, чтобы время работы передавалось в функцию main

2023-10-22 11:23 UTC, GrandpaKaseki commented on main.py
> +            self.time_list.append(f"{time.localtime().tm_hour}:{time.localtime().tm_min}:{time.localtime().tm_sec}")
Переделал

2023-10-22 11:24 UTC, GrandpaKaseki commented on main.py
>          return requests.get('https://www.cbr-xml-daily.ru/daily_json.js').json()
Насколько я знаю, нас устраивает только ответ 200, поэтому сделал так, что если будет какой-то другой ответ, то вернёт None

2023-11-06 16:05 UTC, arybin93 approved these changes
Вроде стало лучше, спасибо за работу! 
Можно мёржить, только разрешить конфликт)

2023-11-11 09:21 UTC, merged